### ISSUE TITLE
AttributeError: module 'glm' has no attribute 'vec3'

### ISSUE THREAD

**Issue by Cursky** [aliyun/NeWCRFs#25]
AttributeError: module 'glm' has no attribute 'vec3'
AttributeError: module 'glm' has no attribute 'mat4'
i run demo but i cant continue with frame , error is glm has no attribute mat4 and vec3 ;
i test all version by glm ,my os is win11 python 3.9.12 ;
hope u can help me,thank u

**Comment by xqh5201314** [comment]
hi，did you save this problem?

**Comment by Cursky** [comment]
No，我没解决这个问题，好兄弟如果你解决了麻烦在这里说一下 谢谢哈~（i cant svae this problem,if u save this problem,colud u respone this issue ,thank !）

**Comment by VanHoo** [comment]
Hello,
I did pip uninstall glm and pip install PyGLM and the problem was solved. Hope it will work for you !

**Comment by xqh5201314** [comment]
thank you very much!did you test with your webcam?



---Original---
From: ***@***.***&gt;
Date: Wed, Oct 5, 2022 20:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [aliyun/NeWCRFs] AttributeError: module 'glm' has no attribute 'vec3' (Issue #25)




 
Hello,
 I did pip uninstall glm and pip install PyGLM and the problem was solved. Hope it will work for you !

**Comment by VanHoo** [comment]
Yes and it works fine :)

**Comment by Zyjer888** [comment]
buchuo，buchuo！
